[package]
name = "booking_api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.9.0"
chrono = "0.4.38"
postgres = "0.19.8"
serde = "1.0.208"
